services:
  postgres:
    image: postgres:18-alpine
    container_name: substrack-postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME:postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:password}
      POSTGRES_DB: ${DB_NAME:substrack}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres_data: