server:
  port: 8080

spring:
  application:
    name: SubsTrack
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/substrack}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=24h

  web:
    error:
      include-binding-errors: always
      include-message: always
      include-stacktrace: never

  task:
    scheduling:
      pool:
        size: 5

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.wilczewski.substrack: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
